/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.facitec.mec.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import py.edu.facitec.mec.controller.CiudadController;
import py.edu.facitec.mec.controller.CiudadControllerImplem;
import py.edu.facitec.mec.model.Ciudad;

/**
 *
 * @author user
 */
public class ForCiudadConsulta extends javax.swing.JDialog {

    /**
     * Creates new form ForCiudadConsulta
     */
    CiudadController controller;
    DefaultTableModel ModeloTabla; 
    public ForCiudadConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller= new CiudadControllerImplem();
        ModeloTabla= (DefaultTableModel)jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCodigoCliente = new javax.swing.JTextField();
        tvBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        xtselecionar = new javax.swing.JButton();
        xtsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");
        setBackground(java.awt.Color.black);
        setForeground(new java.awt.Color(204, 0, 102));
        setPreferredSize(new java.awt.Dimension(500, 500));

        tvBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_software_imagenes/search_64.png"))); // NOI18N
        tvBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Iso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        xtselecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_software_imagenes/Apply.png"))); // NOI18N
        xtselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtselecionarActionPerformed(evt);
            }
        });

        xtsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_software_imagenes/delete_64.png"))); // NOI18N
        xtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(xtselecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(xtsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tvBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tvBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtselecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xtsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(tvBuscar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tvBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvBuscarActionPerformed

     BuscarCliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_tvBuscarActionPerformed

    private void xtselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtselecionarActionPerformed
 selecionarCliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_xtselecionarActionPerformed

    private void xtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtsalirActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
    }//GEN-LAST:event_xtsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForCiudadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForCiudadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForCiudadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForCiudadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForCiudadConsulta dialog = new ForCiudadConsulta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfCodigoCliente;
    private javax.swing.JButton tvBuscar;
    private javax.swing.JButton xtsalir;
    private javax.swing.JButton xtselecionar;
    // End of variables declaration//GEN-END:variables

    private void BuscarCliente() {
     
        List <Ciudad> ciudad = controller.recuperarPorFiltro(tfCodigoCliente.getText());
       String []columnas={"codigo","nombre","iso"};
       Object [][] fila= new Object[ciudad.size()][columnas.length];
       
        for (int i = 0; i < ciudad.size(); i++) {
            fila[i][0]= ciudad.get(i).getCodigo();
            fila[i][1]= ciudad.get(i).getNombre();
            fila[i][2]= ciudad.get(i).getIso();
          
            
        }
        ModeloTabla= new DefaultTableModel(fila,columnas);
       this.jTable1.setModel(ModeloTabla);
    }

    private void selecionarCliente() {
    int codigo= (Integer)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
    ForCiudad.tfcodigo.setText(codigo+"");
    ForCiudad.btnConsultar.doClick();
        dispose();
    }
    private void limpiarTabla(){
    ModeloTabla.setRowCount(0);
}
    
}
