/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.facitec.mec.view;

import java.awt.event.KeyEvent;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import py.edu.facitec.mec.controller.CiudadController;
import py.edu.facitec.mec.controller.CiudadControllerImplem;
import py.edu.facitec.mec.model.Ciudad;

/**
 *
 * @author user
 */
public class ForCiudad extends javax.swing.JFrame {

    
  CiudadController controller;
  
    /**
     * Creates new form ForCiudad
     */
    public ForCiudad() {
        initComponents();
      controller = new CiudadControllerImplem();
           
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        tfnombre = new javax.swing.JTextField();
        tfiso = new javax.swing.JTextField();
        xxGuardar = new javax.swing.JButton();
        tfestado = new javax.swing.JCheckBox();
        btncancelar = new javax.swing.JButton();
        tfeliminar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("iso:");

        jLabel4.setText("estado:");

        tfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoActionPerformed(evt);
            }
        });
        tfcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcodigoKeyPressed(evt);
            }
        });

        tfnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombreActionPerformed(evt);
            }
        });
        tfnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnombreKeyPressed(evt);
            }
        });

        tfiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfisoActionPerformed(evt);
            }
        });
        tfiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfisoKeyPressed(evt);
            }
        });

        xxGuardar.setText("guardar");
        xxGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xxGuardarActionPerformed(evt);
            }
        });

        tfestado.setText("inactivo");
        tfestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfestadoActionPerformed(evt);
            }
        });

        btncancelar.setText("cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        tfeliminar.setText("eliminar");
        tfeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfeliminarActionPerformed(evt);
            }
        });

        btncerrar.setText("cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnConsultar.setText("consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfestado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfiso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(xxGuardar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addGap(31, 31, 31)
                .addComponent(tfeliminar)
                .addGap(18, 18, 18)
                .addComponent(btncerrar)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xxGuardar)
                    .addComponent(btncancelar)
                    .addComponent(tfeliminar)
                    .addComponent(btncerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfestadoActionPerformed
        if (tfestado.isSelected()) {
          tfestado.setLabel("activo");
        }else{
            tfestado.setLabel("inactivo");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tfestadoActionPerformed

    private void tfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoActionPerformed

    private void tfnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreActionPerformed

    private void tfisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfisoActionPerformed

    private void xxGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xxGuardarActionPerformed
     if (tfcodigo.getText().isEmpty()) {
            guardarCiudad();
            limpiar();
            JOptionPane.showMessageDialog(this, "cliente guardado");
        }else{
            
            modificarCiudad();
            limpiar();
            JOptionPane.showMessageDialog(this, "cliente modificcado");
             boolean validar = validarCampos();
        if(validar){
        }
     }
        
            // TODO add your handling code here:
    }//GEN-LAST:event_xxGuardarActionPerformed

    private void tfeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfeliminarActionPerformed

 eliminar();
        // TODO add your handling code here:
    }//GEN-LAST:event_tfeliminarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (tfcodigo.getText().isEmpty()) {
             ForCiudadConsulta consulta= new ForCiudadConsulta(this,true);
  consulta.setVisible(true);
  
        }else{
            consultarCiudad();
        }
        
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void tfcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodigoKeyPressed
   
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoKeyPressed

    private void tfnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnombreKeyPressed
saltoEnter(evt, tfnombre);
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreKeyPressed

    private void tfisoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfisoKeyPressed
  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tfisoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnConsultar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField tfcodigo;
    public static javax.swing.JButton tfeliminar;
    private javax.swing.JCheckBox tfestado;
    private javax.swing.JTextField tfiso;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JButton xxGuardar;
    // End of variables declaration//GEN-END:variables

    private void guardarCiudad() {
     Ciudad ciudad = new Ciudad();
     ciudad.setNombre(tfnombre.getText());
     ciudad.setIso(tfiso.getText());
     ciudad.setEstado(tfestado.isSelected());
             controller.guardar(ciudad);
         
     }
    
    private void modificarCiudad(){
        Ciudad ciu = new Ciudad(
                Integer.parseInt(tfcodigo.getText()),
                tfnombre.getText(),
                tfiso.getText(),
                tfestado.isSelected());
        controller.modificar(ciu);
        
        
            
        }

    private void limpiar() {
   tfcodigo.requestFocus();
        tfcodigo.setText("");
        tfnombre.setText("");
        tfiso.setText("");
        tfestado.setSelected(false);
    }

    private void eliminar() {
         int opcion = JOptionPane.showConfirmDialog(this, "Eliminar?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            
            controller.eliminar( Integer.parseInt( tfcodigo.getText() ) );
            
        }
        limpiar();
            
        }

    private void consultarCiudad() {
     Ciudad ciudad = controller.recuperarPorCodigo(Integer.parseInt(tfcodigo.getText()));
    tfnombre.setText(ciudad.getNombre());
    tfiso.setText(ciudad.getIso());
    }

    private void saltoEnter(java.awt.event.KeyEvent evt, JComponent source) {
   if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            source.requestFocus();
    
    }
    }
    private boolean validarCampos(){
        boolean valido = false;
        if(tfnombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo Nombres es obligatorio", "Aviso", 1);
            tfnombre.requestFocus();
        }else if(tfiso.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo ISO es obligatorio", "Aviso", 1);
            tfiso.requestFocus();
        }else{
            valido = true;
        }
        return valido;
    }
}

    
    
    
        
   
    
    
